### ISSUE TITLE
Day1

### ISSUE THREAD

**Issue by ShubhamRasal** [creators-by-heart/logic-building#1]
**- [ ] Write a program which print sentence on the console as "Jay Ganesh".

- [x] write a program that prints multiple sentences on the console.

- [x] Write a program that accepts a number from a user and print that number.

- [x] write a program which accepts a number in floating-point and print number.

- [x] Write a program that accepts one integer and one character from the user and prints both.

- [x] Write a program that accepts name from user and print that String.
     Input:India is my country  <with space>
    output:India is my country

- [x] Write a program that accepts one character from the user and check whether that is capital or small.
 Input: P   Output:Capital

- [x] write a program that accepts one number from the user and checks that number is greater than 100 or not.
INPUT: 101   OUTPUT: Greater

- [x] write a program which accepts one character from user and store it into memory 
       and print it an address of that character.

- [x] write a program that accepts two numbers and prints the difference between those numbers.
INPUT: 10   3     OUTPUT: 7**

Please create a new branch of your name and submit the programs using the commit message as "Day1"
@creators-by-heart/logic-building

**Comment by ShrutiMane33** [comment]
[day1.txt](https://github.com/creators-by-heart/logic-building/files/5515772/day1.txt)

**Comment by ShubhamRasal** [comment]
again opened for other members

**Comment by ShubhamRasal** [comment]
[Day 1 programs ](https://github.com/creators-by-heart/logic-building/tree/shubham)
